version: '3.8'

services:
  django:
    build: .
    command: gunicorn textanalyzer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A textanalyzer worker --loglevel=debug
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx  # Ensure this path is correct and points to the directory with your Dockerfile and nginx.conf
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static  # Assuming your static files are collected here
      - media_volume:/app/media    # Assuming your media files are stored here
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:
