# Generated by Django 4.2.7 on 2023-11-14 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('submission_text', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('flesch_reading_ease', models.FloatField(blank=True, null=True)),
                ('smog_index', models.FloatField(blank=True, null=True)),
                ('flesch_kincaid_grade', models.FloatField(blank=True, null=True)),
                ('coleman_liau_index', models.FloatField(blank=True, null=True)),
                ('automated_readability_index', models.FloatField(blank=True, null=True)),
                ('dale_chall_readability_score', models.FloatField(blank=True, null=True)),
                ('difficult_words', models.IntegerField(blank=True, null=True)),
                ('linsear_write_formula', models.FloatField(blank=True, null=True)),
                ('gunning_fog', models.FloatField(blank=True, null=True)),
                ('text_standard', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
