# Generated by Django 4.2.7 on 2023-11-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadabilityTestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('more_info_link', models.URLField()),
            ],
        ),
    ]
