# Generated by Django 4.2.7 on 2023-11-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_readabilitytestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='readabilitytestinfo',
            name='display_name',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
