# Generated by Django 4.2.7 on 2023-11-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_readabilitytestinfo_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readabilitytestinfo',
            name='display_name',
        ),
    ]
