# Generated by Django 4.2.7 on 2023-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_remove_readabilitytestinfo_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='readabilitytestinfo',
            name='display_name',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
